# Generated by Django 4.0.6 on 2022-12-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_fakelelements_element_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakid',
            name='contract_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.contragent'),
        ),
    ]
