# Generated by Django 4.0.6 on 2022-12-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_fakid_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakid',
            name='data_padej',
            field=models.DateField(blank=True, null=True),
        ),
    ]
