# Generated by Django 4.0.6 on 2022-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_fakid_data_padej'),
    ]

    operations = [
        migrations.AddField(
            model_name='contragent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
