# Generated by Django 4.1.3 on 2022-12-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mpass", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personinformationmodel",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mpass.groupmodel"
            ),
        ),
    ]
