# Generated by Django 4.1.3 on 2022-12-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpass', '0003_onlyinhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlyinhouse',
            name='when_come',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
